services:
  - type: web
    name: api-facturacion
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-sparkling-rain-ah9axsnz-pooler.c-3.us-east-1.aws.neon.tech/neondb
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_DgqNbetAx68S
      - key: SPRING_DATASOURCE_HIKARI_DATA-SOURCE-PROPERTIES_SSLMODE
        value: require
      - key: PORT
        value: 8080